# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 05:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import query.models
import scanner.types_pb2


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bbox', query.models.ProtoField(scanner.types_pb2.BoundingBox)),
            ],
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=256)),
                ('num_frames', models.IntegerField()),
                ('fps', models.FloatField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='frame',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.Video'),
        ),
        migrations.AddField(
            model_name='face',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.Frame'),
        ),
        migrations.AddField(
            model_name='face',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.Person'),
        ),
    ]
