# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-27 02:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import query.base_models
import scanner.types_pb2


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='krishna_Face',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='krishna_FaceFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='krishna_FaceInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bbox', query.base_models.ProtoField(scanner.types_pb2.BoundingBox)),
                ('concept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='faceinstance', to='query.krishna_Face')),
            ],
        ),
        migrations.CreateModel(
            name='krishna_Frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='krishna_Labeler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='krishna_Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=256)),
                ('num_frames', models.IntegerField()),
                ('fps', models.FloatField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('station', models.CharField(max_length=256)),
                ('show', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='tvnews_Face',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='tvnews_FaceFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='tvnews_FaceInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bbox', query.base_models.ProtoField(scanner.types_pb2.BoundingBox)),
                ('concept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='faceinstance', to='query.tvnews_Face')),
            ],
        ),
        migrations.CreateModel(
            name='tvnews_Frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='tvnews_Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='tvnews_Identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='tvnews_Labeler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='tvnews_Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=256)),
                ('num_frames', models.IntegerField()),
                ('fps', models.FloatField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('station', models.CharField(max_length=256)),
                ('show', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='tvnews_frame',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='frame', to='query.tvnews_Video'),
        ),
        migrations.AddField(
            model_name='tvnews_faceinstance',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='faceinstance', to='query.tvnews_Frame'),
        ),
        migrations.AddField(
            model_name='tvnews_faceinstance',
            name='labeler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='faceinstance', to='query.tvnews_Labeler'),
        ),
        migrations.AddField(
            model_name='tvnews_facefeatures',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='facefeatures', to='query.tvnews_FaceInstance'),
        ),
        migrations.AddField(
            model_name='tvnews_facefeatures',
            name='labeler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='facefeatures', to='query.tvnews_Labeler'),
        ),
        migrations.AddField(
            model_name='tvnews_face',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='query.tvnews_Gender'),
        ),
        migrations.AddField(
            model_name='tvnews_face',
            name='identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='query.tvnews_Identity'),
        ),
        migrations.AddField(
            model_name='krishna_frame',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='frame', to='query.krishna_Video'),
        ),
        migrations.AddField(
            model_name='krishna_faceinstance',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='faceinstance', to='query.krishna_Frame'),
        ),
        migrations.AddField(
            model_name='krishna_faceinstance',
            name='labeler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='faceinstance', to='query.krishna_Labeler'),
        ),
        migrations.AddField(
            model_name='krishna_facefeatures',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='facefeatures', to='query.krishna_FaceInstance'),
        ),
        migrations.AddField(
            model_name='krishna_facefeatures',
            name='labeler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='facefeatures', to='query.krishna_Labeler'),
        ),
        migrations.AlterUniqueTogether(
            name='tvnews_faceinstance',
            unique_together=set([('concept', 'frame')]),
        ),
        migrations.AlterUniqueTogether(
            name='tvnews_facefeatures',
            unique_together=set([('labeler', 'instance')]),
        ),
        migrations.AlterUniqueTogether(
            name='krishna_faceinstance',
            unique_together=set([('concept', 'frame')]),
        ),
        migrations.AlterUniqueTogether(
            name='krishna_facefeatures',
            unique_together=set([('labeler', 'instance')]),
        ),
    ]
