# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-20 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import query.models
import scanner.types_pb2


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='DetectorsUsed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.Detector')),
            ],
        ),
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame', models.IntegerField()),
                ('bbox', query.models.ProtoField(scanner.types_pb2.BoundingBox)),
                ('features', models.TextField()),
                ('gender', models.CharField(default=b'0', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('classifier', models.BinaryField()),
                ('cohesion', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LabelSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_frame', models.IntegerField()),
                ('last_frame', models.IntegerField()),
                ('is_male', models.NullBooleanField()),
                ('labelset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.LabelSet')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=256)),
                ('num_frames', models.IntegerField()),
                ('fps', models.FloatField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='labelset',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.Video'),
        ),
        migrations.AddField(
            model_name='identity',
            name='labelset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.LabelSet'),
        ),
        migrations.AddField(
            model_name='face',
            name='identity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='query.Identity'),
        ),
        migrations.AddField(
            model_name='face',
            name='labelset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.LabelSet'),
        ),
        migrations.AddField(
            model_name='face',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='query.Track'),
        ),
        migrations.AddField(
            model_name='detectorsused',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.LabelSet'),
        ),
    ]
