# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-20 22:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import query.base_models
import scanner.types_pb2


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commercial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommercialInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bbox', query.base_models.ProtoField(scanner.types_pb2.BoundingBox)),
                ('concept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='query.Commercial')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FaceFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', models.BinaryField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FaceInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bbox', query.base_models.ProtoField(scanner.types_pb2.BoundingBox)),
                ('concept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='query.Face')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Labeler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=256)),
                ('num_frames', models.IntegerField()),
                ('fps', models.FloatField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('station', models.CharField(max_length=256)),
                ('show', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='frame',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.Video'),
        ),
        migrations.AddField(
            model_name='faceinstance',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.Frame'),
        ),
        migrations.AddField(
            model_name='faceinstance',
            name='labeler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.Labeler'),
        ),
        migrations.AddField(
            model_name='facefeatures',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.FaceInstance'),
        ),
        migrations.AddField(
            model_name='facefeatures',
            name='labeler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.Labeler'),
        ),
        migrations.AddField(
            model_name='face',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='query.Gender'),
        ),
        migrations.AddField(
            model_name='face',
            name='identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='query.Identity'),
        ),
        migrations.AddField(
            model_name='commercialinstance',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.Frame'),
        ),
        migrations.AddField(
            model_name='commercialinstance',
            name='labeler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.Labeler'),
        ),
        migrations.AlterUniqueTogether(
            name='faceinstance',
            unique_together=set([('concept', 'frame')]),
        ),
        migrations.AlterUniqueTogether(
            name='facefeatures',
            unique_together=set([('labeler', 'instance')]),
        ),
        migrations.AlterUniqueTogether(
            name='commercialinstance',
            unique_together=set([('concept', 'frame')]),
        ),
    ]
