# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-04 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import query.base_models
import scanner.types_pb2


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='krishna_Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='krishna_PersonFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='krishna_PersonInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bbox', query.base_models.ProtoField(scanner.types_pb2.BoundingBox)),
                ('concept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='personinstance', to='query.krishna_Person')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='krishna_frame',
            unique_together=set([('number', 'video')]),
        ),
        migrations.AlterUniqueTogether(
            name='tvnews_frame',
            unique_together=set([('number', 'video')]),
        ),
        migrations.AddField(
            model_name='krishna_personinstance',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='personinstance', to='query.krishna_Frame'),
        ),
        migrations.AddField(
            model_name='krishna_personinstance',
            name='labeler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='personinstance', to='query.krishna_Labeler'),
        ),
        migrations.AddField(
            model_name='krishna_personfeatures',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='personfeatures', to='query.krishna_PersonInstance'),
        ),
        migrations.AddField(
            model_name='krishna_personfeatures',
            name='labeler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='personfeatures', to='query.krishna_Labeler'),
        ),
        migrations.AlterUniqueTogether(
            name='krishna_personinstance',
            unique_together=set([('concept', 'frame')]),
        ),
        migrations.AlterUniqueTogether(
            name='krishna_personfeatures',
            unique_together=set([('labeler', 'instance')]),
        ),
    ]
