# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-11 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='krishna_video',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='tvnews_video',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='tvnews_frame',
            name='talking_heads',
            field=models.BooleanField(default=False),
        ),
    ]
