# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-29 23:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='features',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='face',
            name='identity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='query.Identity'),
        ),
    ]
