# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-22 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('labelset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.LabelSet')),
            ],
        ),
        migrations.RemoveField(
            model_name='face',
            name='labelset',
        ),
        migrations.RemoveField(
            model_name='track',
            name='labelset',
        ),
        migrations.AlterField(
            model_name='face',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.Frame'),
        ),
        migrations.AlterField(
            model_name='track',
            name='first_frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_frame', to='query.Frame'),
        ),
        migrations.AlterField(
            model_name='track',
            name='last_frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_frame', to='query.Frame'),
        ),
    ]
