# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-11 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='krishna_Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='krishna_PersonFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='krishna_PersonInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bbox_x1', models.FloatField(null=True)),
                ('bbox_x2', models.FloatField(null=True)),
                ('bbox_y1', models.FloatField(null=True)),
                ('bbox_y2', models.FloatField(null=True)),
                ('bbox_score', models.FloatField(null=True)),
                ('concept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='personinstance', to='query.krishna_Person')),
            ],
        ),
        migrations.RemoveField(
            model_name='krishna_faceinstance',
            name='bbox',
        ),
        migrations.RemoveField(
            model_name='tvnews_faceinstance',
            name='bbox',
        ),
        migrations.AddField(
            model_name='krishna_faceinstance',
            name='bbox_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='krishna_faceinstance',
            name='bbox_x1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='krishna_faceinstance',
            name='bbox_x2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='krishna_faceinstance',
            name='bbox_y1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='krishna_faceinstance',
            name='bbox_y2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tvnews_faceinstance',
            name='bbox_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tvnews_faceinstance',
            name='bbox_x1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tvnews_faceinstance',
            name='bbox_x2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tvnews_faceinstance',
            name='bbox_y1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tvnews_faceinstance',
            name='bbox_y2',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='krishna_frame',
            name='number',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='krishna_labeler',
            name='name',
            field=models.CharField(db_index=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='krishna_video',
            name='path',
            field=models.CharField(db_index=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='tvnews_frame',
            name='number',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='tvnews_labeler',
            name='name',
            field=models.CharField(db_index=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='tvnews_video',
            name='path',
            field=models.CharField(db_index=True, max_length=256),
        ),
        migrations.AlterUniqueTogether(
            name='krishna_frame',
            unique_together=set([('video', 'number')]),
        ),
        migrations.AlterUniqueTogether(
            name='tvnews_frame',
            unique_together=set([('video', 'number')]),
        ),
        migrations.AddField(
            model_name='krishna_personinstance',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='personinstance', to='query.krishna_Frame'),
        ),
        migrations.AddField(
            model_name='krishna_personinstance',
            name='labeler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='personinstance', to='query.krishna_Labeler'),
        ),
        migrations.AddField(
            model_name='krishna_personfeatures',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='personfeatures', to='query.krishna_PersonInstance'),
        ),
        migrations.AddField(
            model_name='krishna_personfeatures',
            name='labeler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='personfeatures', to='query.krishna_Labeler'),
        ),
        migrations.AlterUniqueTogether(
            name='krishna_personinstance',
            unique_together=set([('concept', 'frame')]),
        ),
        migrations.AlterUniqueTogether(
            name='krishna_personfeatures',
            unique_together=set([('labeler', 'instance')]),
        ),
    ]
