# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-01 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0002_auto_20170529_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='gender',
            field=models.CharField(default=b'U', max_length=2),
        ),
    ]
