# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-22 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0002_auto_20170622_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='is_male',
        ),
        migrations.AddField(
            model_name='track',
            name='gender',
            field=models.CharField(default=b'0', max_length=2),
        ),
    ]
