# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-12 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0002_auto_20171011_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='krishna_faceinstance',
            name='bbox_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='krishna_faceinstance',
            name='bbox_x1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='krishna_faceinstance',
            name='bbox_x2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='krishna_faceinstance',
            name='bbox_y1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='krishna_faceinstance',
            name='bbox_y2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='krishna_personinstance',
            name='bbox_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='krishna_personinstance',
            name='bbox_x1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='krishna_personinstance',
            name='bbox_x2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='krishna_personinstance',
            name='bbox_y1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='krishna_personinstance',
            name='bbox_y2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tvnews_faceinstance',
            name='bbox_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tvnews_faceinstance',
            name='bbox_x1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tvnews_faceinstance',
            name='bbox_x2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tvnews_faceinstance',
            name='bbox_y1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tvnews_faceinstance',
            name='bbox_y2',
            field=models.FloatField(null=True),
        ),
    ]
