# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-04 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0002_auto_20170904_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='krishna_frame',
            name='number',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='krishna_labeler',
            name='name',
            field=models.CharField(db_index=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='krishna_video',
            name='path',
            field=models.CharField(db_index=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='tvnews_frame',
            name='number',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='tvnews_labeler',
            name='name',
            field=models.CharField(db_index=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='tvnews_video',
            name='path',
            field=models.CharField(db_index=True, max_length=256),
        ),
    ]
