# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-04 23:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0003_auto_20170904_1536'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='krishna_frame',
            unique_together=set([('video', 'number')]),
        ),
        migrations.AlterUniqueTogether(
            name='tvnews_frame',
            unique_together=set([('video', 'number')]),
        ),
    ]
