# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-09 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0003_auto_20171107_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='tvnews_Pose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bbox_x1', models.FloatField()),
                ('bbox_x2', models.FloatField()),
                ('bbox_y1', models.FloatField()),
                ('bbox_y2', models.FloatField()),
                ('bbox_score', models.FloatField()),
                ('keypoints', models.BinaryField()),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='pose', to='query.tvnews_Frame')),
                ('labeler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='pose', to='query.tvnews_Labeler')),
            ],
        ),
        migrations.CreateModel(
            name='tvnews_PoseFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', models.BinaryField()),
                ('labeler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='posefeatures', to='query.tvnews_Labeler')),
                ('pose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='posefeatures', to='query.tvnews_Pose')),
            ],
        ),
        migrations.CreateModel(
            name='tvnews_PoseTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keypoints', models.BinaryField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='tvnews_pose',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='pose', to='query.tvnews_PoseTrack'),
        ),
        migrations.AlterUniqueTogether(
            name='tvnews_posefeatures',
            unique_together=set([('labeler', 'pose')]),
        ),
        migrations.AlterUniqueTogether(
            name='tvnews_pose',
            unique_together=set([('track', 'frame', 'labeler')]),
        ),
    ]
