# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-21 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0003_auto_20170622_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='query.Video'),
        ),
    ]
