# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-15 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0003_face_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='gender',
            field=models.CharField(default=b'0', max_length=2),
        ),
    ]
