# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-12 01:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0003_auto_20171011_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='krishna_faceinstance',
            name='bbox',
        ),
        migrations.RemoveField(
            model_name='krishna_personinstance',
            name='bbox',
        ),
        migrations.RemoveField(
            model_name='tvnews_faceinstance',
            name='bbox',
        ),
    ]
