# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-13 06:04
from __future__ import unicode_literals

from django.db import migrations, models
from query.base_models import ModelDelegator
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0004_auto_20171011_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='krishna_facefeatures',
            old_name='instance',
            new_name='faceinstance', ),
        migrations.RenameField(
            model_name='krishna_personfeatures',
            old_name='instance',
            new_name='personinstance', ),
        migrations.RenameField(
            model_name='tvnews_facefeatures',
            old_name='instance',
            new_name='faceinstance', ),
        migrations.RenameField(
            model_name='krishna_faceinstance', old_name='concept', new_name='face'),
        migrations.RenameField(
            model_name='krishna_personinstance', old_name='concept', new_name='person'),
        migrations.RenameField(
            model_name='tvnews_faceinstance', old_name='concept', new_name='face'),
        migrations.AlterField(
            model_name='krishna_faceinstance',
            name='bbox_score',
            field=models.FloatField(default=0.0),
            preserve_default=False, ),
        migrations.AlterField(
            model_name='krishna_faceinstance',
            name='bbox_x1',
            field=models.FloatField(default=0.0),
            preserve_default=False, ),
        migrations.AlterField(
            model_name='krishna_faceinstance',
            name='bbox_x2',
            field=models.FloatField(default=0.0),
            preserve_default=False, ),
        migrations.AlterField(
            model_name='krishna_faceinstance',
            name='bbox_y1',
            field=models.FloatField(default=0.0),
            preserve_default=False, ),
        migrations.AlterField(
            model_name='krishna_faceinstance',
            name='bbox_y2',
            field=models.FloatField(default=0.0),
            preserve_default=False, ),
        migrations.AlterField(
            model_name='krishna_personinstance',
            name='bbox_score',
            field=models.FloatField(default=0.0),
            preserve_default=False, ),
        migrations.AlterField(
            model_name='krishna_personinstance',
            name='bbox_x1',
            field=models.FloatField(default=0.0),
            preserve_default=False, ),
        migrations.AlterField(
            model_name='krishna_personinstance',
            name='bbox_x2',
            field=models.FloatField(default=0.0),
            preserve_default=False, ),
        migrations.AlterField(
            model_name='krishna_personinstance',
            name='bbox_y1',
            field=models.FloatField(default=0.0),
            preserve_default=False, ),
        migrations.AlterField(
            model_name='krishna_personinstance',
            name='bbox_y2',
            field=models.FloatField(default=0.0),
            preserve_default=False, ),
        migrations.AlterField(
            model_name='tvnews_faceinstance',
            name='bbox_score',
            field=models.FloatField(default=0.0),
            preserve_default=False, ),
        migrations.AlterField(
            model_name='tvnews_faceinstance',
            name='bbox_x1',
            field=models.FloatField(default=0.0),
            preserve_default=False, ),
        migrations.AlterField(
            model_name='tvnews_faceinstance',
            name='bbox_x2',
            field=models.FloatField(default=0.0),
            preserve_default=False, ),
        migrations.AlterField(
            model_name='tvnews_faceinstance',
            name='bbox_y1',
            field=models.FloatField(default=0.0),
            preserve_default=False, ),
        migrations.AlterField(
            model_name='tvnews_faceinstance',
            name='bbox_y2',
            field=models.FloatField(default=0.0),
            preserve_default=False, ),
        migrations.AlterUniqueTogether(
            name='krishna_facefeatures',
            unique_together=set([('labeler', 'faceinstance')]), ),
        migrations.AlterUniqueTogether(
            name='krishna_faceinstance',
            unique_together=set([('face', 'frame', 'labeler')]), ),
        migrations.AlterUniqueTogether(
            name='krishna_personfeatures',
            unique_together=set([('labeler', 'personinstance')]), ),
        migrations.AlterUniqueTogether(
            name='krishna_personinstance',
            unique_together=set([('person', 'frame', 'labeler')]), ),
        migrations.AlterUniqueTogether(
            name='tvnews_facefeatures',
            unique_together=set([('labeler', 'faceinstance')]), ),
        migrations.AlterUniqueTogether(
            name='tvnews_faceinstance',
            unique_together=set([('face', 'frame', 'labeler')]), ),
    ]
