# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-09 21:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0004_auto_20170904_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tvnews_video',
            old_name='station',
            new_name='channel',
        ),
        migrations.RemoveField(
            model_name='krishna_video',
            name='show',
        ),
        migrations.RemoveField(
            model_name='krishna_video',
            name='station',
        ),
        migrations.AddField(
            model_name='tvnews_video',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
