# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-21 21:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0004_track_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='first_frame',
        ),
        migrations.RemoveField(
            model_name='track',
            name='last_frame',
        ),
    ]
