# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-18 02:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0006_auto_20171015_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvnews_faceinstance',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='query.tvnews_Gender'),
        ),
        migrations.AddField(
            model_name='tvnews_faceinstance',
            name='identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='query.tvnews_Identity'),
        ),
    ]
