# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-24 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0007_auto_20171017_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='krishna_faceinstance',
            name='face',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='faceinstance', to='query.krishna_Face'),
        ),
        migrations.AlterField(
            model_name='krishna_personinstance',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='personinstance', to='query.krishna_Person'),
        ),
        migrations.AlterField(
            model_name='tvnews_faceinstance',
            name='face',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='faceinstance', to='query.tvnews_Face'),
        ),
    ]
