# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-03 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import query.base_models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tvnews_Commercial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='tvnews_CommercialTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_frame', models.IntegerField()),
                ('max_frame', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='tvnews_Face',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bbox_x1', models.FloatField()),
                ('bbox_x2', models.FloatField()),
                ('bbox_y1', models.FloatField()),
                ('bbox_y2', models.FloatField()),
                ('bbox_score', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, query.base_models.BoundingBox),
        ),
        migrations.CreateModel(
            name='tvnews_FaceFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', models.BinaryField()),
                ('face', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='facefeatures', to='query.tvnews_Face')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, query.base_models.Features),
        ),
        migrations.CreateModel(
            name='tvnews_FaceGender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='facegender', to='query.tvnews_Face')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='tvnews_Frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='tvnews_Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='tvnews_Identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='tvnews_IdentityLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='identitylabel', to='query.tvnews_Identity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='tvnews_Labeler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='tvnews_Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='person', to='query.tvnews_Frame')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='tvnews_PersonTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_frame', models.IntegerField()),
                ('max_frame', models.IntegerField()),
                ('labeler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='persontrack', to='query.tvnews_Labeler')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='tvnews_Pose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keypoints', models.BinaryField()),
                ('labeler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='pose', to='query.tvnews_Labeler')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='pose', to='query.tvnews_Person')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, query.base_models.Pose),
        ),
        migrations.CreateModel(
            name='tvnews_Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=256)),
                ('num_frames', models.IntegerField()),
                ('fps', models.FloatField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('channel', models.CharField(max_length=256)),
                ('show', models.CharField(max_length=256)),
                ('time', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='tvnews_persontrack',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='persontrack', to='query.tvnews_Video'),
        ),
        migrations.AddField(
            model_name='tvnews_person',
            name='tracks',
            field=models.ManyToManyField(related_query_name='person', to='query.tvnews_PersonTrack'),
        ),
        migrations.AddField(
            model_name='tvnews_identitylabel',
            name='labeler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='identitylabel', to='query.tvnews_Labeler'),
        ),
        migrations.AddField(
            model_name='tvnews_identitylabel',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='identitylabel', to='query.tvnews_Person'),
        ),
        migrations.AddField(
            model_name='tvnews_frame',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='frame', to='query.tvnews_Video'),
        ),
        migrations.AddField(
            model_name='tvnews_facegender',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='facegender', to='query.tvnews_Gender'),
        ),
        migrations.AddField(
            model_name='tvnews_facegender',
            name='labeler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='facegender', to='query.tvnews_Labeler'),
        ),
        migrations.AddField(
            model_name='tvnews_facefeatures',
            name='labeler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='facefeatures', to='query.tvnews_Labeler'),
        ),
        migrations.AddField(
            model_name='tvnews_face',
            name='labeler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='face', to='query.tvnews_Labeler'),
        ),
        migrations.AddField(
            model_name='tvnews_face',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='face', to='query.tvnews_Person'),
        ),
        migrations.AddField(
            model_name='tvnews_commercialtrack',
            name='labeler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='commercialtrack', to='query.tvnews_Labeler'),
        ),
        migrations.AddField(
            model_name='tvnews_commercialtrack',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='commercialtrack', to='query.tvnews_Video'),
        ),
        migrations.AddField(
            model_name='tvnews_commercial',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='commercial', to='query.tvnews_Frame'),
        ),
        migrations.AddField(
            model_name='tvnews_commercial',
            name='tracks',
            field=models.ManyToManyField(related_query_name='commercial', to='query.tvnews_CommercialTrack'),
        ),
        migrations.AlterUniqueTogether(
            name='tvnews_frame',
            unique_together=set([('video', 'number')]),
        ),
    ]
