# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-03 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0001_initial'),
    ]

    operations = [
        # migrations.RenameModel(
        #     old_name='FaceTrack',
        #     new_name='tvnews_FaceTrack',
        # ),
    ]
