# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-04 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvnews_facefeatures',
            name='distto',
            field=models.FloatField(null=True),
        ),
    ]
