# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvnews_face',
            name='blurriness',
            field=models.FloatField(null=True),
        ),
    ]
