# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceidentity',
            name='probability',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='labeler',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='labeler',
            name='data_path',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
