# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-04 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import query.base_models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0002_tvnews_facefeatures_distto'),
    ]

    operations = [
        migrations.CreateModel(
            name='default_Face',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bbox_x1', models.FloatField()),
                ('bbox_x2', models.FloatField()),
                ('bbox_y1', models.FloatField()),
                ('bbox_y2', models.FloatField()),
                ('bbox_score', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, query.base_models.BoundingBox),
        ),
        migrations.CreateModel(
            name='default_FaceFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', models.BinaryField()),
                ('distto', models.FloatField(null=True)),
                ('face', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='facefeatures', to='query.default_Face')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, query.base_models.Features),
        ),
        migrations.CreateModel(
            name='default_FaceGender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='facegender', to='query.default_Face')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='default_Frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='default_Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='default_Labeler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='default_Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='person', to='query.default_Frame')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='default_PersonTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_frame', models.IntegerField()),
                ('max_frame', models.IntegerField()),
                ('labeler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='persontrack', to='query.default_Labeler')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='default_Pose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keypoints', models.BinaryField()),
                ('labeler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='pose', to='query.default_Labeler')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='pose', to='query.default_Person')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, query.base_models.Pose),
        ),
        migrations.CreateModel(
            name='default_Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=256)),
                ('num_frames', models.IntegerField()),
                ('fps', models.FloatField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='default_persontrack',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='persontrack', to='query.default_Video'),
        ),
        migrations.AddField(
            model_name='default_person',
            name='tracks',
            field=models.ManyToManyField(related_query_name='person', to='query.default_PersonTrack'),
        ),
        migrations.AddField(
            model_name='default_frame',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='frame', to='query.default_Video'),
        ),
        migrations.AddField(
            model_name='default_facegender',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='facegender', to='query.default_Gender'),
        ),
        migrations.AddField(
            model_name='default_facegender',
            name='labeler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='facegender', to='query.default_Labeler'),
        ),
        migrations.AddField(
            model_name='default_facefeatures',
            name='labeler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='facefeatures', to='query.default_Labeler'),
        ),
        migrations.AddField(
            model_name='default_face',
            name='labeler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='face', to='query.default_Labeler'),
        ),
        migrations.AddField(
            model_name='default_face',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='face', to='query.default_Person'),
        ),
        migrations.AlterUniqueTogether(
            name='default_frame',
            unique_together=set([('video', 'number')]),
        ),
    ]
