# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-11 11:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0003_tvnews_job'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tvnews_Job',
            new_name='tvnews_ScannerJob',
        ),
    ]
