# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-05 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0003_auto_20171204_0243'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tvnews_face',
            unique_together=set([('labeler', 'person')]),
        ),
        migrations.AlterUniqueTogether(
            name='tvnews_facefeatures',
            unique_together=set([('labeler', 'face')]),
        ),
        migrations.AlterUniqueTogether(
            name='tvnews_facegender',
            unique_together=set([('labeler', 'face')]),
        ),
        migrations.AlterUniqueTogether(
            name='tvnews_pose',
            unique_together=set([('labeler', 'person')]),
        ),
    ]
