# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-22 17:32
from __future__ import unicode_literals

from django.db import migrations as m

tables = ['channel', 'commercial', 'face', 'facefeatures', 'facegender',
          'faceidentity', 'frame', 'gender', 'identity', 'labeler',
          'person', 'pose', 'scannerjob', 'segment', 'shot', 'show',
          'speaker', 'tag', 'thing', 'thingtype', 'video', 'videotag']

class Migration(m.Migration):

    dependencies = [
        ('query', '0004_auto_20180511_1143'),
    ]


    operations = [
        m.RenameModel('tvnews_{}'.format(t), t)
        for t in tables
    ]
