# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-12 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0004_auto_20180612_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canonicalshow',
            name='is_prime_time',
        ),
        migrations.RemoveField(
            model_name='canonicalshow',
            name='is_weekend',
        ),
    ]
