# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-05 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0004_auto_20171205_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='tvnews_Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='tvnews_Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='tvnews_video',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='tvnews_video',
            name='show',
        ),
    ]
