# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-13 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0005_auto_20171112_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='babycam_pose',
            name='keypoints',
            field=models.BinaryField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tvnews_pose',
            name='keypoints',
            field=models.BinaryField(default=None),
            preserve_default=False,
        ),
    ]
