# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-05 23:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0005_auto_20171205_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvnews_video',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='video', to='query.tvnews_Channel'),
        ),
        migrations.AddField(
            model_name='tvnews_video',
            name='show',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='video', to='query.tvnews_Show'),
        ),
    ]
