# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-12 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0005_auto_20180612_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='canonical_show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.CanonicalShow'),
        ),
    ]
