# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-14 00:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0006_auto_20171112_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='default_Face',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bbox_x1', models.FloatField()),
                ('bbox_x2', models.FloatField()),
                ('bbox_y1', models.FloatField()),
                ('bbox_y2', models.FloatField()),
                ('bbox_score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='default_FaceFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', models.BinaryField()),
                ('face', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='facefeatures', to='query.default_Face')),
            ],
        ),
        migrations.CreateModel(
            name='default_FaceTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='default_Frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='default_Labeler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='default_Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=256)),
                ('num_frames', models.IntegerField()),
                ('fps', models.FloatField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='default_frame',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='frame', to='query.default_Video'),
        ),
        migrations.AddField(
            model_name='default_facefeatures',
            name='labeler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='facefeatures', to='query.default_Labeler'),
        ),
        migrations.AddField(
            model_name='default_face',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='face', to='query.default_Frame'),
        ),
        migrations.AddField(
            model_name='default_face',
            name='labeler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='face', to='query.default_Labeler'),
        ),
        migrations.AddField(
            model_name='default_face',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='face', to='query.default_FaceTrack'),
        ),
        migrations.AlterUniqueTogether(
            name='default_frame',
            unique_together=set([('video', 'number')]),
        ),
        migrations.AlterUniqueTogether(
            name='default_facefeatures',
            unique_together=set([('labeler', 'face')]),
        ),
        migrations.AlterUniqueTogether(
            name='default_face',
            unique_together=set([('track', 'frame', 'labeler')]),
        ),
    ]
