# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-15 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0006_auto_20180612_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='canonicalshow',
            name='hosts',
            field=models.ManyToManyField(blank=True, to='query.Thing'),
        ),
    ]
