# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-25 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0007_canonicalshow_hosts'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='probability',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='facegender',
            name='probability',
            field=models.FloatField(default=1.0),
        ),
    ]
