# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-07 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0007_auto_20171205_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='default_video',
            name='has_captions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tvnews_video',
            name='has_captions',
            field=models.BooleanField(default=False),
        ),
    ]
