# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-22 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0008_auto_20171119_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babycam_face',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='face', to='query.babycam_FaceTrack'),
        ),
        migrations.AlterField(
            model_name='babycam_pose',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='pose', to='query.babycam_PoseTrack'),
        ),
        migrations.AlterField(
            model_name='default_face',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='face', to='query.default_FaceTrack'),
        ),
        migrations.AlterField(
            model_name='default_pose',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='pose', to='query.default_PoseTrack'),
        ),
        migrations.AlterField(
            model_name='tvnews_face',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='face', to='query.tvnews_FaceTrack'),
        ),
        migrations.AlterField(
            model_name='tvnews_pose',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='pose', to='query.tvnews_PoseTrack'),
        ),
    ]
