# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-25 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0008_auto_20180625_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bbox_x1', models.FloatField()),
                ('bbox_x2', models.FloatField()),
                ('bbox_y1', models.FloatField()),
                ('bbox_y2', models.FloatField()),
                ('bbox_score', models.FloatField()),
                ('cls', models.IntegerField()),
                ('probability', models.FloatField()),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.Frame')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
