# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-07 23:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0009_tvnews_topic_tvnews_topictrack'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvnews_topictrack',
            name='topic',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_query_name='topictrack', to='query.tvnews_Topic'),
            preserve_default=False,
        ),
    ]
