# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-23 02:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0009_auto_20171122_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='default_Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('face', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='gender', to='query.default_Face')),
                ('labeler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='gender', to='query.default_Labeler')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
