# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-25 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0009_object'),
    ]

    operations = [
        migrations.RenameField(
            model_name='object',
            old_name='cls',
            new_name='label',
        ),
    ]
