# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-13 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0011_tvnews_tag_tvnews_videotag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvnews_videotag',
            name='fps',
        ),
        migrations.RemoveField(
            model_name='tvnews_videotag',
            name='has_captions',
        ),
        migrations.RemoveField(
            model_name='tvnews_videotag',
            name='height',
        ),
        migrations.RemoveField(
            model_name='tvnews_videotag',
            name='num_frames',
        ),
        migrations.RemoveField(
            model_name='tvnews_videotag',
            name='path',
        ),
        migrations.RemoveField(
            model_name='tvnews_videotag',
            name='width',
        ),
    ]
