# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-25 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0012_auto_20180712_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='threeyears_dataset',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='faceidentity',
            name='probability',
            field=models.FloatField(default=1.0),
        ),
    ]
