# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0012_auto_20171213_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='tvnews_Shot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_frame', models.IntegerField()),
                ('max_frame', models.IntegerField()),
                ('labeler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='shot', to='query.tvnews_Labeler')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='shot', to='query.tvnews_Video')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
