# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-26 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0014_auto_20180926_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faceidentity',
            name='identity',
        ),
        migrations.AlterField(
            model_name='faceidentity',
            name='identity2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.Identity'),
        ),
    ]
