# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-26 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0015_auto_20180926_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='canonicalshow',
            name='hosts2',
            field=models.ManyToManyField(blank=True, to='query.Identity'),
        ),
        migrations.AddField(
            model_name='show',
            name='hosts2',
            field=models.ManyToManyField(blank=True, to='query.Identity'),
        ),
    ]
