# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0015_tvnews_face_shot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvnews_commercialtrack',
            name='labeler',
        ),
        migrations.RemoveField(
            model_name='tvnews_commercialtrack',
            name='video',
        ),
        migrations.RemoveField(
            model_name='tvnews_commercial',
            name='frame',
        ),
        migrations.RemoveField(
            model_name='tvnews_commercial',
            name='tracks',
        ),
        migrations.AddField(
            model_name='tvnews_commercial',
            name='labeler',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_query_name='commercial', to='query.tvnews_Labeler'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tvnews_commercial',
            name='max_frame',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tvnews_commercial',
            name='min_frame',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tvnews_commercial',
            name='video',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_query_name='commercial', to='query.tvnews_Video'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='tvnews_CommercialTrack',
        ),
    ]
