# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-26 20:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0016_auto_20180926_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canonicalshow',
            name='hosts',
        ),
        migrations.RemoveField(
            model_name='show',
            name='hosts',
        ),
    ]
