# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-26 20:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0017_auto_20180926_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='canonicalshow',
            old_name='hosts2',
            new_name='hosts',
        ),
        migrations.RenameField(
            model_name='faceidentity',
            old_name='identity2',
            new_name='identity',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='hosts2',
            new_name='hosts',
        ),
    ]
