# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0017_auto_20180122_1729'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tvnews_thing',
            unique_together=set([('name', 'type')]),
        ),
    ]
