# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0018_auto_20180122_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvnews_segment',
            name='polarity',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tvnews_segment',
            name='subjectivity',
            field=models.FloatField(null=True),
        ),
    ]
