# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-26 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0019_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='topics',
            field=models.ManyToManyField(to='query.Topic'),
        ),
    ]
