# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-24 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0019_auto_20180122_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvnews_shot',
            name='in_commercial',
            field=models.BooleanField(default=False),
        ),
    ]
