# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-28 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0021_auto_20180926_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='shot_boundary',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
