# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0021_tvnews_video_commercials_labeled'),
    ]

    operations = [
        migrations.CreateModel(
            name='tvnews_FaceIdentity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='faceidentity', to='query.tvnews_Face')),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='faceidentity', to='query.tvnews_Thing')),
                ('labeler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='faceidentity', to='query.tvnews_Labeler')),
            ],
        ),
        migrations.RemoveField(
            model_name='tvnews_identitylabel',
            name='identity',
        ),
        migrations.RemoveField(
            model_name='tvnews_identitylabel',
            name='labeler',
        ),
        migrations.RemoveField(
            model_name='tvnews_identitylabel',
            name='person',
        ),
        migrations.DeleteModel(
            name='tvnews_Identity',
        ),
        migrations.DeleteModel(
            name='tvnews_IdentityLabel',
        ),
        migrations.AlterUniqueTogether(
            name='tvnews_faceidentity',
            unique_together=set([('labeler', 'face')]),
        ),
    ]
