# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-26 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0021_auto_20180926_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LabeledCommercial',
            fields=[
                ('timesegment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='query.TimeSegment')),
            ],
            bases=('query.timesegment',),
        ),
        migrations.CreateModel(
            name='LabeledInterview',
            fields=[
                ('timesegment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='query.TimeSegment')),
                ('original', models.BooleanField(default=True)),
                ('scattered_clips', models.BooleanField(default=False)),
                ('interviewer1', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('interviewer2', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('guest1', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('guest2', models.CharField(blank=True, default=None, max_length=256, null=True)),
            ],
            bases=('query.timesegment',),
        ),
        migrations.CreateModel(
            name='LabeledPanel',
            fields=[
                ('timesegment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='query.TimeSegment')),
                ('num_panelists', models.IntegerField()),
            ],
            bases=('query.timesegment',),
        ),
        migrations.AddField(
            model_name='timesegment',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.Video'),
        ),
    ]
