# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-26 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0022_auto_20181026_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labeledcommercial',
            name='timesegment_ptr',
        ),
        migrations.RemoveField(
            model_name='labeledinterview',
            name='timesegment_ptr',
        ),
        migrations.RemoveField(
            model_name='labeledpanel',
            name='timesegment_ptr',
        ),
        migrations.RemoveField(
            model_name='timesegment',
            name='video',
        ),
        migrations.DeleteModel(
            name='LabeledCommercial',
        ),
        migrations.DeleteModel(
            name='LabeledInterview',
        ),
        migrations.DeleteModel(
            name='LabeledPanel',
        ),
        migrations.DeleteModel(
            name='TimeSegment',
        ),
    ]
