# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-01 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0022_frame_shot_boundary'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='frame',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='query.Frame'),
        ),
        migrations.AddField(
            model_name='pose',
            name='frame',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='query.Frame'),
        ),
        migrations.AlterUniqueTogether(
            name='face',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='pose',
            unique_together=set([]),
        ),
    ]
