# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0023_tvnews_face_background'),
    ]

    operations = [
        migrations.CreateModel(
            name='tvnews_ThingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='tvnews_topictrack',
            name='labeler',
        ),
        migrations.RemoveField(
            model_name='tvnews_topictrack',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='tvnews_topictrack',
            name='video',
        ),
        migrations.DeleteModel(
            name='tvnews_Topic',
        ),
        migrations.DeleteModel(
            name='tvnews_TopicTrack',
        ),
    ]
