# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-03 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0023_auto_20181101_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='frame',
        ),
        migrations.RemoveField(
            model_name='pose',
            name='person',
        ),
        migrations.AlterField(
            model_name='face',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.Frame'),
        ),
        migrations.AlterField(
            model_name='pose',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.Frame'),
        ),
        migrations.RemoveField(
            model_name='face',
            name='person',
        ),
        migrations.AlterUniqueTogether(
            name='face',
            unique_together=set([('labeler', 'frame', 'bbox_x1', 'bbox_x2', 'bbox_y1', 'bbox_y2')]),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
