# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0024_auto_20180228_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvnews_thing',
            name='type2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='thing', to='query.tvnews_ThingType'),
        ),
    ]
