# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-27 18:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0024_labeledcommercial_labeledinterview_labeledpanel'),
        ('query', '0024_auto_20181103_2019'),
    ]

    operations = [
    ]
