# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0025_tvnews_thing_type2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvnews_thing',
            name='type2',
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_query_name='thing',
                to='query.tvnews_ThingType'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='tvnews_thing',
            name='type',
        ),
        migrations.AlterUniqueTogether(
            name='tvnews_thing',
            unique_together=set([('name', 'type2')]),
        ),
    ]
