# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-27 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0025_merge_20181227_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='HairColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='HairColorName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='haircolor',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.HairColorName'),
        ),
        migrations.AddField(
            model_name='haircolor',
            name='face',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.Face'),
        ),
        migrations.AddField(
            model_name='haircolor',
            name='labeler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.Labeler'),
        ),
        migrations.AlterUniqueTogether(
            name='haircolor',
            unique_together=set([('labeler', 'face')]),
        ),
    ]
