# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-27 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0026_auto_20181227_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haircolorname',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
