# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0026_auto_20180228_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tvnews_thing',
            old_name='type2',
            new_name='type',
        ),
        migrations.AlterUniqueTogether(
            name='tvnews_thing',
            unique_together=set([('name', 'type')]),
        ),
    ]
