# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-01 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0027_auto_20181227_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ClothingName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='clothing',
            name='clothing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.ClothingName'),
        ),
        migrations.AddField(
            model_name='clothing',
            name='face',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.Face'),
        ),
        migrations.AddField(
            model_name='clothing',
            name='labeler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.Labeler'),
        ),
        migrations.AlterUniqueTogether(
            name='clothing',
            unique_together=set([('labeler', 'face')]),
        ),
    ]
