# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-01 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0027_auto_20180228_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='tvnews_Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_frame', models.IntegerField()),
                ('max_frame', models.IntegerField()),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='speaker', to='query.tvnews_Gender')),
                ('labeler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='speaker', to='query.tvnews_Labeler')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='speaker', to='query.tvnews_Video')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='tvnews_persontrack',
            name='labeler',
        ),
        migrations.RemoveField(
            model_name='tvnews_persontrack',
            name='video',
        ),
        migrations.RemoveField(
            model_name='tvnews_person',
            name='tracks',
        ),
        migrations.DeleteModel(
            name='tvnews_PersonTrack',
        ),
    ]
