# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-03 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0028_auto_20181228_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duplicate',
            field=models.BooleanField(default=False),
        ),
    ]
