# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-21 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0028_auto_20180301_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvnews_face',
            name='is_host',
            field=models.BooleanField(default=False),
        ),
    ]
