# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-28 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0029_tvnews_face_is_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='tvnews_Identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='identity', to='query.tvnews_Thing')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='tvnews_speaker',
            name='identity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='speaker', to='query.tvnews_Identity'),
        ),
    ]
