# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-28 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0030_auto_20180328_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvnews_identity',
            name='thing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='identity', to='query.tvnews_Thing'),
        ),
        migrations.AlterField(
            model_name='tvnews_identity',
            name='name',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
