# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-05 10:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0028_auto_20190101_2032'),
        ('query', '0030_video_corrupted'),
    ]

    operations = [
    ]
