# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-06 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0031_merge_20190105_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='HairLength',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.Face')),
                ('labeler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.Labeler')),
            ],
        ),
        migrations.CreateModel(
            name='HairLengthName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='hairlength',
            name='length',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.HairLengthName'),
        ),
        migrations.AlterUniqueTogether(
            name='hairlength',
            unique_together=set([('labeler', 'face')]),
        ),
    ]
