# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-11 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0032_auto_20190106_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=1.0)),
                ('face', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.Face')),
                ('labeler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.Labeler')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='IdentityTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='identity',
            name='tags',
            field=models.ManyToManyField(blank=True, to='query.IdentityTag'),
        ),
        migrations.AlterUniqueTogether(
            name='facetag',
            unique_together=set([('labeler', 'face')]),
        ),
    ]
