# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-11 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0033_auto_20190311_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameSampler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='frame',
            name='sampler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='query.FrameSampler'),
        ),
    ]
